### ISSUE TITLE
Has pensado en realizar el algoritmo inverso: NUT-text-to-number?

### ISSUE THREAD

**Issue by SalvaJ** [emrahyumuk/NUT-number-to-text#1]
Hola:

Existen bastantes algoritmos para convertir números a (texto) letras en idioma Español, en los lenguajes de programación más usados.  Yo mismo escribí uno hace algunos años en Visual Basic que convertía importes en euros a palabras para su uso como macro en Word.

Ahora necesitaba justo lo contrario.  Después de mucho buscar tanto en Github, como en Sourceforge y en Google en general, no he encontrado ningún algoritmo en ningún lenguaje de programación que realice la conversión de texto a número en idioma Español.  No sé si es que dicho algoritmo es de poca utilidad (no lo creo, su uso en _data mining_, análisis lexicográficos de dominios y redes sociales,...) o su difícil implementación en el idioma Español (con numerosas irregularidades) han provocado la inexistencia de algoritmo alguno en código abierto.  No me cabe duda de que existen soluciones propietarias en programas de OCR, _speech-to-text_,\* data mining_, pero el problema es que no hay *_ninguno Open Source**.

Después de repasar el código de algún algoritmo para idioma Inglés tuve que descartar su implementación al idioma Español y decidí partir de cero.

Si te interesa lo tienes en https://github.com/SalvaJ/Words2Num_es 
Cualquier ayuda o colaboración será bienvenida.

Saludos.

**Comment by emrahyumuk** [comment]
Thank you for the issue. Can you check the last verison of Nut?
